### ISSUE TITLE
locator.go

### ISSUE THREAD

**Issue by dikako** [sleeper-inc/go-web-auto#10]
Map locator keys to selectors

- Changes to use .yml file
- Support specifier string %s
- Priority pertama element:
- -- User centric
- -- But can still use traditional element

**User Centric interaction**
```
Given User fill "Field Username" with "myuser"
When User fill "Field Password" with "myPassword"
And User click "Login"
```

**Custom Element**
```
# login_element.yml
username:
  - id: inputUsername
  - xpath: //div[@name= "button_login"]
```
```
Given User fill "Username" with "myuser"
When User fill "Field Password" with "myPassword"
And Use
```

- without prefix: find element base on user centric
- with prefix `~`: call key from .yml file

# User centric
fill: tag input
click: button, link text, aria-label, radio-button
assert:
